Repository atharvatechnology/ronb-node, pull requests merged in 2022-09, with the labels that each got.

#71 Order comments by creation date
  src/comments/comments.service.ts
  src/common/pagination/types/page-data.ts
  src/news/news.resolver.ts
  src/news/news.service.ts
  src/schema.gql
Labels: bug, enhancement

#72 Display current time in paginated data
  src/comments/comments.resolver.ts
  src/common/pagination/types/page-data.ts
  src/news/news.resolver.ts
Labels: enhancement

#73 Add NewsState enum type in news creation input.
  src/news/dto/create-news.input.ts
  src/schema.gql
Labels: bug

#78 Build error fix
  Dockerfile
  package-lock.json
  package.json
Labels: bug

#80 add event_time in Notification
  src/notifications/notifications.service.ts
Labels: enhancement

#81 Parse string user id to int in security.
  package-lock.json
  src/common/middlewares/security.middleware.ts
Labels: bug

#83 Set user to null for unauthorized access.
  src/common/middlewares/security.middleware.ts
Labels: bug

#85 Remove &nbsp; from notification body
  package-lock.json
  package.json
  src/notifications/notifications.service.ts
Labels: enhancement

#86 Mulitple reacts in the user likes for comments, reply and news.
  src/comments/comments.resolver.ts
  src/comments/comments.service.ts
  src/comments/dto/create-comment.input.ts
  src/comments/dto/update-comment.input.ts
  src/comments/entities/comment.entity.ts
  src/common/entities/base.entity.ts
  src/migrations/1663070262638-add_multiple_user_reacts.ts
  src/migrations/1664429565022-add_haha_user_react.ts
  src/news/dto/create-news.input.ts
  src/news/news.service.ts
  src/schema.gql
Labels: :new: feature
