Repository atharvatechnology/ronb-node, pull requests merged in 2022-08, with the labels that each got.

#43 Tagging
  src/app.module.ts
  src/common/utils/slugify.ts
  src/migrations/1658999859548-tag_create.ts
  src/migrations/1659075085846-create_new_tags_with_relation.ts
  src/migrations/1659611338321-remove_slug_from_tags.ts
  src/news/entities/news.entity.ts
  src/news/news.module.ts
  src/news/news.resolver.ts
  src/news/news.service.ts
  src/schema.gql
  src/tags/dto/create-tag.input.ts
  src/tags/dto/filter-news-tags.ts
  src/tags/dto/update-tag.input.ts
  src/tags/entities/tag.entity.ts
  src/tags/tags.module.ts
  src/tags/tags.resolver.spec.ts
  src/tags/tags.resolver.ts
  src/tags/tags.service.spec.ts
  src/tags/tags.service.ts
Labels: :new: feature

#48 update readme for migration flow
  README.md
Labels: documentation

#47 Django node inter backend authentication.
  package-lock.json
  package.json
  src/app.module.ts
  src/common/decorators/user.decorator.ts
  src/common/middlewares/security.middleware.ts
  src/common/utils/checkUserAuthentication.ts
  src/main.ts
  src/news/news.resolver.ts
  src/news/news.service.ts
Labels: enhancement

#51 Add comments feature
  package-lock.json
  package.json
  src/app.module.ts
  src/comments/comments.module.ts
  src/comments/comments.resolver.spec.ts
  src/comments/comments.resolver.ts
  src/comments/comments.service.spec.ts
  src/comments/comments.service.ts
  src/comments/dto/create-comment.input.ts
  src/comments/dto/update-comment.input.ts
  src/comments/entities/comment.entity.ts
  src/common/entities/base.entity.ts
  src/common/middlewares/security.middleware.ts
  src/common/utils/checkUserAuthentication.ts
  src/migrations/1660022679384-update_news_parameters.ts
  src/migrations/1660113922661-cascade_delete_news_comments_n_replies.ts
  src/news/entities/news.entity.ts
  src/news/news.module.ts
  src/news/news.resolver.ts
  src/news/news.service.ts
  src/schema.gql
  src/tags/tags.module.ts
  src/tags/tags.service.ts
  template.env
Labels: enhancement

#53 Resolve graphql upload and fs capacitor version mismatch.
  package-lock.json
  package.json
Labels: enhancement

#54 squahed all migration into single
  src/migrations/1658657469005-create-news-public-toilet.ts
  src/migrations/1658809584544-add_new_category_likes_update.ts
  src/migrations/1658999859548-tag_create.ts
  src/migrations/1659075085846-create_new_tags_with_relation.ts
  src/migrations/1659611338321-remove_slug_from_tags.ts
  src/migrations/1660022679384-update_news_parameters.ts
  src/migrations/1660113922661-cascade_delete_news_comments_n_replies.ts
  src/migrations/1660460891479-news_tags_toilet_migration.ts
Labels: enhancement

#58 Like news comments and replies
  src/comments/comments.module.ts
  src/comments/comments.resolver.ts
  src/comments/comments.service.ts
  src/comments/entities/comment.entity.ts
  src/common/entities/base.entity.ts
  src/common/middlewares/security.middleware.ts
  src/migrations/1660568383928-add_likes_in_newsComment.ts
  src/migrations/1660632385705-add_like_in_news_reply.ts
  src/news/news.resolver.ts
  src/news/news.service.ts
  src/schema.gql
Labels: enhancement

#59 Pagination in news and reply
  package-lock.json
  package.json
  src/app.module.ts
  src/comments/comments.module.ts
  src/comments/comments.resolver.ts
  src/comments/comments.response.ts
  src/comments/comments.service.ts
  src/common/middlewares/security.middleware.ts
  src/schema.gql
  template.env
Labels: enhancement

#62 Upload and retrieve news images from s3.
  .gitignore
  package-lock.json
  package.json
  src/common/middlewares/pathfinder.middleware.ts
  src/common/utils/upload.ts
  src/config/datasource.ts
  src/news/entities/news.entity.ts
  src/news/news.service.ts
  template.env
Labels: enhancement

#67 News pin publish
  src/migrations/1661505886498-remove_name_add_title_required.ts
  src/migrations/1661508763753-add_news_status_and_pinned_fields.ts
  src/news/dto/create-news.input.ts
  src/news/entities/news.entity.ts
  src/news/news.service.ts
  src/schema.gql
Labels: enhancement

#63 Check permission for user
  src/comments/comments.module.ts
  src/comments/comments.resolver.ts
  src/comments/comments.service.ts
Labels: enhancement

#68 remove published filter and manage aws upload key
  src/common/utils/upload.ts
  src/news/news.service.ts
Labels: enhancement

#69 Resolve profile information for author
  src/app.module.ts
  src/comments/comments.resolver.ts
  src/comments/comments.service.ts
  src/comments/entities/comment.entity.ts
  src/common/middlewares/pathfinder.middleware.ts
  src/common/services/files.service.ts
  src/common/utils/upload.ts
  src/migrations/1661508763753-add_news_status_and_pinned_fields.ts
  src/news/news.module.ts
  src/news/news.resolver.ts
  src/news/news.service.ts
  src/schema.gql
Labels: enhancement
