Repository atharvatechnology/ronb-node, pull requests merged in 2022-12, with the labels that each got.

#90 Add Notification on comment and reaction
  src/comments/comments.module.ts
  src/comments/comments.resolver.ts
  src/comments/comments.service.ts
  src/comments/comments.subscriber.ts
  src/migrations/1667281554966-user_with_notification_device.ts
  src/migrations/1667283004886-notification_device_add_updated_at.ts
  src/migrations/1667468467526-add_user_field_notification.ts
  src/notifications/dto/create-notification.input.ts
  src/notifications/entities/notifications.entity.ts
  src/notifications/notifications.module.ts
  src/notifications/notifications.resolver.ts
  src/notifications/notifications.response.ts
  src/notifications/notifications.service.ts
  src/schema.gql
Labels: enhancement

#91 CICD to aws instance.
  .github/workflows/build-deploy-aws.yml
  .github/workflows/build-deploy.yml
  .github/workflows/downscale.yml
  .github/workflows/upscale.yml
Labels: enhancement, deployment

#92 Tag the images created and supply as env to deploy.
  .github/workflows/build-deploy-aws.yml
Labels: deployment

#98 Add user interests feature.
  src/comments/comments.service.ts
  src/migrations/1672400929046-create_user_interests.ts
  src/news/dto/create-news.input.ts
  src/news/entities/news.entity.ts
  src/news/news.module.ts
  src/news/news.resolver.ts
  src/news/news.service.ts
  src/schema.gql
  src/tags/entities/tag.entity.ts
  src/tags/tags.service.ts
Labels: enhancement, :new: feature

#99 Remove engagement duration.
  src/migrations/1672400929046-create_user_interests.ts
Labels: bug, enhancement
