Repository atharvatechnology/ronb-node, pull requests merged in 2023-02, with the labels that each got.

#132 Added count value in admin find all for yellow pages
  package-lock.json
  package.json
  src/migrations/1675225469934-create_email_for_yellow_pages_update_fields_of_yellow_pages_entities.ts
  src/schema.gql
  src/yellow-pages/dto/create-yellow-pages.input.ts
  src/yellow-pages/entities/yellow-pages.entity.ts
  src/yellow-pages/yellow-pages.module.ts
  src/yellow-pages/yellow-pages.resolver.ts
  src/yellow-pages/yellow-pages.response.ts
  src/yellow-pages/yellow-pages.service.ts
Labels: enhancement

#131 Handle user interest creation.
  src/news/dto/create-news.input.ts
  src/news/news.resolver.ts
  src/news/news.service.ts
  src/schema.gql
  src/users/users.module.ts
Labels: bug, enhancement

#135 Release 1.1
  src/news/dto/create-news.input.ts
  src/news/news.resolver.ts
  src/news/news.service.ts
  src/schema.gql
  src/users/users.module.ts
Labels: deployment

#134 Add feature custom notification and link to app
  .vscode/settings.json
  src/notifications/entities/notifications.entity.ts
  src/notifications/notifications.resolver.ts
  src/notifications/notifications.service.ts
  src/schema.gql
Labels: enhancement

#136 custom notification
  .vscode/settings.json
  src/notifications/entities/notifications.entity.ts
  src/notifications/notifications.resolver.ts
  src/notifications/notifications.service.ts
  src/schema.gql
Labels: enhancement

#137 Add release versions to github actions build.
  .github/workflows/build-deploy-aws.yml
Labels: enhancement

#138 Deployment
  .github/workflows/build-deploy-aws.yml
Labels: enhancement, deployment

#139 Select only first image tag while setting env variables for img name.
  .github/workflows/build-deploy-aws.yml
Labels: enhancement, deployment

#140 Deployment
  .github/workflows/build-deploy-aws.yml
Labels: deployment

#141 Added search feature for yellowpages for both app and admin
  src/schema.gql
  src/yellow-pages/dto/filter-yellowpages.input.ts
  src/yellow-pages/yellow-pages.resolver.ts
  src/yellow-pages/yellow-pages.service.ts
Labels: enhancement

#142 Added single Image for Yellow pages
  src/migrations/1675849453872-add_fields_single_image_and_published_at_for_yellowpages.ts
  src/schema.gql
  src/yellow-pages/dto/create-yellow-pages.input.ts
  src/yellow-pages/entities/yellow-pages.entity.ts
  src/yellow-pages/yellow-pages.module.ts
  src/yellow-pages/yellow-pages.resolver.ts
  src/yellow-pages/yellow-pages.service.ts
Labels: enhancement

#143 Public Toilet
  .github/workflows/build-deploy-aws.yml
  src/public-toilet/public-toilet.module.ts
  src/public-toilet/public-toilet.resolver.ts
  src/public-toilet/public-toilet.service.ts
  src/reviews/reviews.resolver.ts
  src/reviews/reviews.service.ts
  src/schema.gql
Labels: enhancement

#145 New Features
  .github/workflows/build-deploy-aws.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/comments/comments.resolver.ts
  src/common/enum/publish_state.enum.ts
  src/common/guards/roles.guard.ts
  src/common/pagination/fetch-pagination-response.ts
  src/common/utils/checkPublishedState.ts
  src/common/utils/checkUserAuthentication.ts
  src/migrations/1673937077713-new_entities_for_yellowpages.ts
  src/migrations/1673955354346-added_category_description.ts
  src/migrations/1674038684884-create_public_toilet_review_entity.ts
  src/migrations/1674539900224-add_state_in_public_toilet.ts
  src/migrations/1674553469981-author_public_toilet_id_join_primary_key_review.ts
  src/migrations/1674553545485-public_toilet_review_remove_id.ts
  src/migrations/1675225469934-create_email_for_yellow_pages_update_fields_of_yellow_pages_entities.ts
  src/migrations/1675849453872-add_fields_single_image_and_published_at_for_yellowpages.ts
  src/news/dto/create-news.input.ts
  src/news/entities/news.entity.ts
  src/news/news.service.ts
  src/public-toilet/dto/create-public-toilet.input.ts
  src/public-toilet/entities/public-toilet.entity.ts
  src/public-toilet/public-toilet.module.ts
  src/public-toilet/public-toilet.resolver.ts
  src/public-toilet/public-toilet.response.ts
  src/public-toilet/public-toilet.service.ts
  src/reviews/dto/create-reviews.input.ts
  src/reviews/dto/update-reviews.input.ts
  src/reviews/entities/reviews.entity.ts
  src/reviews/reviews.module.ts
  src/reviews/reviews.resolver.ts
  src/reviews/reviews.response.ts
  src/reviews/reviews.service.ts
  src/schema.gql
  src/users/users.resolver.ts
  src/users/users.service.ts
  src/yellow-pages/dto/create-yellow-pages.input.ts
  src/yellow-pages/dto/filter-yellowpages.input.ts
  src/yellow-pages/dto/update-yellow-pages.input.ts
  src/yellow-pages/entities/yellow-pages.entity.ts
  src/yellow-pages/yellow-pages.module.ts
  src/yellow-pages/yellow-pages.resolver.ts
  src/yellow-pages/yellow-pages.response.ts
  src/yellow-pages/yellow-pages.service.ts
Labels: enhancement

#146 Release new features
  .github/workflows/build-deploy-aws.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/comments/comments.resolver.ts
  src/common/enum/publish_state.enum.ts
  src/common/guards/roles.guard.ts
  src/common/pagination/fetch-pagination-response.ts
  src/common/utils/checkPublishedState.ts
  src/common/utils/checkUserAuthentication.ts
  src/migrations/1673937077713-new_entities_for_yellowpages.ts
  src/migrations/1673955354346-added_category_description.ts
  src/migrations/1674038684884-create_public_toilet_review_entity.ts
  src/migrations/1674539900224-add_state_in_public_toilet.ts
  src/migrations/1674553469981-author_public_toilet_id_join_primary_key_review.ts
  src/migrations/1674553545485-public_toilet_review_remove_id.ts
  src/migrations/1675225469934-create_email_for_yellow_pages_update_fields_of_yellow_pages_entities.ts
  src/migrations/1675849453872-add_fields_single_image_and_published_at_for_yellowpages.ts
  src/news/dto/create-news.input.ts
  src/news/entities/news.entity.ts
  src/news/news.service.ts
  src/public-toilet/dto/create-public-toilet.input.ts
  src/public-toilet/entities/public-toilet.entity.ts
  src/public-toilet/public-toilet.module.ts
  src/public-toilet/public-toilet.resolver.ts
  src/public-toilet/public-toilet.response.ts
  src/public-toilet/public-toilet.service.ts
  src/reviews/dto/create-reviews.input.ts
  src/reviews/dto/update-reviews.input.ts
  src/reviews/entities/reviews.entity.ts
  src/reviews/reviews.module.ts
  src/reviews/reviews.resolver.ts
  src/reviews/reviews.response.ts
  src/reviews/reviews.service.ts
  src/schema.gql
  src/users/users.resolver.ts
  src/users/users.service.ts
  src/yellow-pages/dto/create-yellow-pages.input.ts
  src/yellow-pages/dto/filter-yellowpages.input.ts
  src/yellow-pages/dto/update-yellow-pages.input.ts
  src/yellow-pages/entities/yellow-pages.entity.ts
  src/yellow-pages/yellow-pages.module.ts
  src/yellow-pages/yellow-pages.resolver.ts
  src/yellow-pages/yellow-pages.response.ts
  src/yellow-pages/yellow-pages.service.ts
Labels: enhancement
