Repository atharvatechnology/ronb-node, pull requests merged in 2023-01, with the labels that each got.

#104 Filter news
  src/news/dto/filter-news.input.ts
  src/news/news.service.ts
  src/schema.gql
Labels: enhancement

#106 Added pagination for YellowPages
  src/common/pagination/fetch-pagination-input.ts
  src/schema.gql
  src/yellow-pages/yellow-pages.resolver.ts
  src/yellow-pages/yellow-pages.service.ts
Labels: enhancement

#107 migration file issue resolved
  src/migrations/1672121422417-yellow-pages.ts
  src/migrations/1673252412663-add_cascade_delete.ts
  src/migrations/1673331843726-yellow_pages.ts
  src/schema.gql
  src/yellow-pages/yellow-pages.resolver.ts
Labels: enhancement

#108 Implement `IsAdmin` check for admin access control.
  src/common/guards/admin.guard.ts
  src/common/interceptors/errorlogger.interceptor.ts
  src/common/middlewares/security.middleware.ts
  src/yellow-pages/entities/yellow-pages.entity.ts
  src/yellow-pages/yellow-pages.resolver.ts
Labels: enhancement

#109 Develop generic RBAC system for ronb app.
  src/comments/comments.module.ts
  src/common/decorators/public.decorator.ts
  src/common/decorators/roles.decorator.ts
  src/common/decorators/user.decorator.ts
  src/common/enum/role.enum.ts
  src/common/guards/admin.guard.ts
  src/common/guards/roles.guard.ts
  src/common/middlewares/security.middleware.ts
  src/news/entities/news.entity.ts
  src/yellow-pages/yellow-pages.resolver.ts
Labels: enhancement, :new: feature

#113 Fix undefined user id bug.
  src/common/decorators/user.decorator.ts
  src/common/interfaces/user.interface.ts
Labels: bug, enhancement

#111 Add language field in news
  src/migrations/1673605245471-add_language_choice_news.ts
  src/news/dto/create-news.input.ts
  src/news/dto/filter-news.input.ts
  src/news/entities/news.entity.ts
  src/news/news.service.ts
  src/schema.gql
Labels: enhancement

#114 Detect message mismatch with msg identity check.
  src/common/middlewares/security.middleware.ts
Labels: enhancement

#115 Don't set user in request for invalid message.
  src/common/middlewares/security.middleware.ts
Labels: bug

#116 Remove unnecessary console logs.
  src/common/middlewares/security.middleware.ts
Labels: bug

#118 Add fixed Author object on deleted or invalid author in comments
  src/comments/comments.resolver.ts
  src/comments/comments.service.ts
  src/comments/entities/comment.entity.ts
  src/schema.gql
Labels: enhancement

#122 Deployment
  .github/workflows/build-deploy-aws.yml
Labels: deployment

#120 Move user code from comments to user app
  src/app.module.ts
  src/comments/comments.module.ts
  src/comments/comments.resolver.spec.ts
  src/comments/comments.resolver.ts
  src/comments/comments.service.spec.ts
  src/comments/comments.service.ts
  src/comments/comments.subscriber.ts
  src/comments/entities/comment.entity.ts
  src/users/entitiy/users.entity.ts
  src/users/users.module.ts
  src/users/users.resolver.ts
  src/users/users.service.ts
Labels: enhancement

#124 Deployment
  src/app.module.ts
  src/comments/comments.module.ts
  src/comments/comments.resolver.spec.ts
  src/comments/comments.resolver.ts
  src/comments/comments.service.spec.ts
  src/comments/comments.service.ts
  src/comments/comments.subscriber.ts
  src/comments/entities/comment.entity.ts
  src/users/entitiy/users.entity.ts
  src/users/users.module.ts
  src/users/users.resolver.ts
  src/users/users.service.ts
Labels: deployment

#119 Added two new entities for yellow pages: District and Province
  src/common/enum/publish_state.enum.ts
  src/common/guards/roles.guard.ts
  src/migrations/1673937077713-new_entities_for_yellowpages.ts
  src/migrations/1673955354346-added_category_description.ts
  src/news/dto/create-news.input.ts
  src/news/entities/news.entity.ts
  src/schema.gql
  src/yellow-pages/dto/create-yellow-pages.input.ts
  src/yellow-pages/dto/update-yellow-pages.input.ts
  src/yellow-pages/entities/yellow-pages.entity.ts
  src/yellow-pages/yellow-pages.module.ts
Labels: enhancement

#125 Add Review Feature in Public Toilet
  src/app.module.ts
  src/common/pagination/fetch-pagination-response.ts
  src/common/utils/checkPublishedState.ts
  src/common/utils/checkUserAuthentication.ts
  src/migrations/1674038684884-create_public_toilet_review_entity.ts
  src/migrations/1674539900224-add_state_in_public_toilet.ts
  src/migrations/1674553469981-author_public_toilet_id_join_primary_key_review.ts
  src/migrations/1674553545485-public_toilet_review_remove_id.ts
  src/news/news.service.ts
  src/public-toilet/dto/create-public-toilet.input.ts
  src/public-toilet/entities/public-toilet.entity.ts
  src/public-toilet/public-toilet.module.ts
  src/public-toilet/public-toilet.resolver.ts
  src/public-toilet/public-toilet.response.ts
  src/public-toilet/public-toilet.service.ts
  src/reviews/dto/create-reviews.input.ts
  src/reviews/dto/update-reviews.input.ts
  src/reviews/entities/reviews.entity.ts
  src/reviews/reviews.module.ts
  src/reviews/reviews.resolver.ts
  src/reviews/reviews.response.ts
  src/reviews/reviews.service.ts
  src/schema.gql
Labels: enhancement

#128 Obscure user identity on user delete.
  src/comments/comments.resolver.ts
  src/common/guards/roles.guard.ts
  src/news/news.service.ts
  src/users/users.module.ts
  src/users/users.resolver.ts
  src/users/users.service.ts
Labels: enhancement
